version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres-test-tenpo
    environment:
      POSTGRES_DB: test_tenpo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    image: jesusnoriegadev/test-tenpo:latest
    container_name: test-tenpo-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/test_tenpo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  postgres-data:
